import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
    minHeight: '100%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    
    
    
    elevation: 2,
  },
  backButton: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#333333',
  },
  placeholder: {
    width: 44,
  },
  navigation: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  navItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginHorizontal: 3,
    borderRadius: 20,
    backgroundColor: '#F8F9FA',
    borderWidth: 1,
    borderColor: '#E9ECEF',
    
    
    
    elevation: 1,
  },
  navLabel: {
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 6,
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  section: {
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    backgroundColor: '#FFFFFF',
    
    
    
    elevation: 6,
    borderWidth: 1,
    borderColor: '#F0F0F0',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginLeft: 16,
    color: '#333333',
  },
  infoGrid: {
    gap: 8,
  },
  infoItem: {
    padding: 6,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
    color: '#495057',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#6C757D',
  },
  subTermItem: {
    marginTop: 8,
    marginLeft: 12,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: '#DEE2E6',
  },
  subTermLabel: {
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 2,
    color: '#6C757D',
  },
  subTermText: {
    fontSize: 12,
    lineHeight: 18,
    color: '#6C757D',
  },
  resourcesContainer: {
    gap: 6,
  },
  resourcesSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  resourcesIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  resourcesSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginLeft: 12,
    color: '#333333',
  },
  resourcesTitle: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 3,
    marginTop: 4,
    color: '#333333',
    paddingBottom: 3,
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
  },
  videoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    marginBottom: 3,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    elevation: 2,
  },
  videoTitle: {
    fontSize: 12,
    marginLeft: 12,
    flex: 1,
    fontWeight: '600',
    color: '#495057',
  },
  imageItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    marginBottom: 3,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    elevation: 2,
  },
  imageTitle: {
    fontSize: 12,
    marginLeft: 12,
    flex: 1,
    fontWeight: '600',
    color: '#495057',
  },
  repertoireContainer: {
    gap: 12,
  },
  repertoireTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 6,
    color: '#333333',
    paddingBottom: 4,
    borderBottomWidth: 2,
    borderBottomColor: '#E9ECEF',
  },
  songList: {
    gap: 6,
    marginBottom: 12,
  },
  songItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    
    
    
    elevation: 2,
  },
  songName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#495057',
  },
  songLevel: {
    fontSize: 12,
    fontWeight: '700',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#E3F2FD',
    borderRadius: 16,
    color: '#1976D2',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tipsBox: {
    padding: 8,
    borderRadius: 16,
    backgroundColor: '#E8F5E8',
    borderWidth: 1,
    borderColor: '#C8E6C9',
    
    
    
    elevation: 2,
  },
  tipsTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 4,
    color: '#2E7D32',
  },
  tipsText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#388E3C',
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    
    
    
    elevation: 2,
  },
  infoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  cameraButton: {
    padding: 8,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
  },
  infoSubLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 3,
    color: '#495057',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  fingeringImageContainer: {
    marginTop: 8,
    padding: 8,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E9ECEF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fingeringImage: {
    width: '100%',
    minHeight: 200,
    maxHeight: 400,
    borderRadius: 12,
  },
  noteTableScrollView: {
    marginTop: 8,
  },
  noteTableScrollContent: {
    paddingRight: 4,
  },
  noteTableContainer: {
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
    minWidth: 400,
  },
  noteTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  noteTableHeaderCell: {
    flex: 1,
    minWidth: 35,
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#E0E0E0',
  },
  noteTableHeaderText: {
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  noteTableLabelCell: {
    width: 90,
    minWidth: 90,
    maxWidth: 90,
    paddingVertical: 10,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#E0E0E0',
  },
  noteTableLabelText: {
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  noteTableCell: {
    flex: 1,
    minWidth: 35,
    paddingVertical: 10,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#E0E0E0',
  },
  noteTableText: {
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
  },
});
