import React, { createContext, useContext } from 'react';

interface LanguageContextType {
  t: (key: keyof typeof translations) => string;
  /** @deprecated 日本語のみ対応のため常に 'ja' */
  language: 'ja';
  /** @deprecated 言語切り替えは廃止 */
  setLanguage: (lang: 'ja') => void;
}

const translations = {
  // Navigation
  calendar: 'カレンダー',
    timer: 'タイマー',
    goals: '目標',
    tuner: 'チューナー',
    metronome: 'メトロノーム',
    share: '共有',
    practice: '基礎練',
    practiceMenu: '学習ツール',
    settings: 'その他',
    
    // Common
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    add: '追加',
    close: '閉じる',
    start: 'スタート',
    pause: '一時停止',
    reset: 'リセット',
    search: '検索',
    done: '完了',
    copy: 'コピー',
    copyCompleted: 'コピー完了',
    copiedToClipboard: 'がクリップボードにコピーされました',
    
    // Calendar
    practiceCalendar: '練習カレンダー',
    addPracticeRecord: '練習記録を追加',
    practiceTime: '練習時間',
    practiceContent: '練習内容',
    monthlyTotal: '今月の合計練習時間',
    quickRecord: 'クイック記録',
    
    // Timer
    timerMode: 'タイマー',
    stopwatchMode: 'ストップウォッチ',
    customTimeSetting: 'カスタム時間設定',
    quickSetting: 'クイック設定',
    practiceCompleted: '練習完了！',
    recordToCalendar: 'この練習時間をカレンダーに記録しますか？',
    hours: '時間',
    minutes: '分',
    seconds: '秒',
    apply: '適用',
    autoRecord: '次回から自動で記録',
    autoRecordDescription: 'タイマー完了時に自動で練習記録を保存',
    soundOnCompletion: '完了時にサウンド',
    soundOnCompletionDescription: 'タイマー完了時に通知音を再生',
    pleaseSetTimerTime: 'タイマー時間を設定してください',
    settingsCompleted: '設定完了',
    willAutoRecordNextTime: '次回から自動で記録されます',
    timerSetTo: '{time}に設定しました',
    pleaseSetValidTime: '有効な時間を設定してください',
    failedToSavePracticeRecord: '練習記録の保存に失敗しました',
    
    // Goals
    goalSetting: '目標設定',
    personalShort: '個人目標（短期）',
    personalLong: '個人目標（長期）',
    groupGoal: '団体目標',
    addNewGoal: '新しい目標を追加',
    goalTitle: '目標タイトル',
    goalDescription: '詳細説明',
    targetDate: '目標期日',
    progress: '進捗',
    
    // Tuner
    tunerTitle: 'チューナー',
    referenceSound: '基準音再生',
    pitchDetection: '音程検出',
    tuningTips: 'チューニングのコツ',
    cents: 'セント',
    frequency: '周波数',
    featureUnavailable: '機能停止',
    tunerUnavailable: 'チューナー機能は現在利用できません。',
    notSupported: '未対応',
    openStringWebOnly: '開放弦の音はWebでのみ再生できます。',
    failedToPlaySound: '音の再生に失敗しました。',
    
    // Practice
    basicPracticeMenu: 'バイオリンの基礎練メニュー',
    basicPractice: '基礎練',
    beginner: '初級',
    intermediate: '中級',
    advanced: 'マスター',
    basicPracticeMenuFor: '{instrument}の基礎練メニュー',
    
    // Practice Menu
    learningTools: '学習ツール',
    musicDictionary: '音楽用語辞典',
    sightReadingTraining: '譜読みトレーニング',
    
    // Beginner Guide
    faq: 'よくあるQ&A',
    overview: '楽器の基本情報',
    basicPlaying: '基本的な演奏方法',
    fingering: '運指表',
    terminology: '基本楽器用語',
    maintenance: 'メンテナンス',
    tips: '練習のコツ',
    resources: '参考資料',
    basicStructure: '基本構造',
    charm: '魅力',
    history: '歴史・背景',
    features: '特徴',
    famousMusicians: '有名な演奏家',
    howToHold: '楽器の持ち方・構え方',
    howToMakeSound: '基本的な音の出し方',
    fingeringBasics: '基本的な運指表',
    howToUseFingering: '運指表の使い方',
    correctPosture: '正しい姿勢',
    bowHold: '弓の持ち方',
    handPosition: '手の位置',
    leftHand: '左手の使い方',
    embouchure: 'アンブシュア',
    strumming: 'ストラミング（ギター）',
    breathing: '呼吸法（管楽器）',
    fingerUsage: '指の使い方・運指の基礎',
    basicInfo: '基本情報',
    playingMethod: '演奏方法',
    care: 'お手入れ',
    advice: 'アドバイス',
    guide: 'ガイド',
    loading: '読み込み中...',
    maintenanceFrequency: 'メンテナンス頻度の目安',
    practiceTipsAndMindset: '練習のコツ・心構え',
    instrumentGuide: '{instrument}ガイド',
    dailyCare: '日常的なお手入れ',
    storageMethod: '保管方法',
    cleaningFrequency: '洗浄頻度の目安',
    precautions: '注意事項',
    requiredSupplies: '必要な用品',
    beginnerAdvice: '初心者向けアドバイス',
    commonMistakes: 'よくある間違いと対策',
    improvementPoints: '上達のためのポイント',
    tutorialVideos: '解説動画',
    
    // Settings
    other: 'その他',
    profile: 'プロフィール設定',
    appearance: '外観設定',
    language: '言語設定',
    notifications: '通知設定',
    statistics: '統計・分析',
    musicLibrary: '楽曲ライブラリ',
    help: 'ヘルプ・サポート',
    feedback: 'フィードバック',
    privacy: 'プライバシー設定',
    terms: '利用規約',
    logout: 'ログアウト',
    createNewAccount: '新規アカウント作成',
    currentlyLoggedIn: 'ログイン中',
    profileSettings: 'プロフィール設定',
    profileSettingsSubtitle: '個人情報・楽器設定',
    myLibrary: 'マイライブラリ',
    myLibrarySubtitle: '楽曲を整理する',
    recordingsLibrary: '録音ライブラリ',
    recordingsLibrarySubtitle: '演奏を時系列で確認',
    mainFeatures: '主要機能',
    mainFeaturesSubtitle: '楽器選択・外観設定',
    tutorial: 'アプリ使い方ガイド',
    tutorialSubtitle: 'アプリの使い方を詳しく説明',
    notificationSettings: '通知設定',
    notificationSettingsSubtitle: '練習リマインダー・通知方法',
    languageSettings: '言語設定',
    languageSettingsSubtitle: '日本語・English',
    privacySettings: 'プライバシー設定',
    privacySettingsSubtitle: '利用規約・プライバシーポリシー',
    feedbackTitle: 'フィードバック',
    feedbackSubtitle: 'アプリをシェア・レビュー・ランキング',
    logoutTitle: 'ログアウト',
    logoutSubtitle: 'アカウントからログアウト',
    logoutConfirm: 'ログアウト確認',
    logoutMessage: 'ログアウトしますか？\n\nログアウト一個上に配置してあるフィードバックにご協力お願いします',
    logoutFailed: 'ログアウトに失敗しました',
    logoutError: 'ログアウト処理中にエラーが発生しました',
    mainFeaturesSettings: '主要機能設定',
    tunerSettings: 'チューナー',
    instrumentSelection: '楽器選択',
    practiceLevel: '演奏レベル',
    appearanceSettings: '外観設定',
    themeLoading: 'テーマの読み込み中...',
    
    // Auth
    login: 'ログイン',
    signup: '新規会員登録',
    email: 'メールアドレス',
    password: 'パスワード',
    confirmPassword: 'パスワード確認',
    loginRequired: 'ログインが必要です',
    
    // Statistics
    statisticsAnalysis: '統計・分析',
    practiceStatsSummary: '練習統計サマリー',
    totalPracticeTime: '総練習時間',
    totalPracticeDays: '総練習日数',
    dailyAverage: '日平均（分）',
    weeklyAverage: '週平均',
    displayPeriod: '表示期間',
    daily: '日毎',
    monthly: '月毎',
    yearly: '年毎',
    averagePracticeTime: '平均練習時間',
    longestPracticeTime: '最長練習時間',
    practiceDays: '練習日数',
    practicedMonths: '練習した月数',
    practicedSections: '練習した区分数',
    weeklyStats: '週別統計',
    monthlyStats: '月別統計',
    yearlyStats: '年別統計',
    detailedAnalysis: '詳細分析',
    basicStats: '基礎統計',
    longestConsecutiveDays: '最長連続練習日',
    practiceIntensityStats: '練習強度別統計',
    shortTime: '短時間（30分未満）',
    mediumTime: '中時間（30-180分未満）',
    longTime: '長時間（180分以上）',
    times: '回',
    days: '日',
    months: 'ヶ月',
    sections: '区分',
    weekByWeek: '週別',
    monthByMonth: '月別',
    practiceFrequency: '練習頻度',
    weeklyPracticePattern: '週間練習パターン',
    monthlyPracticeTrend: '月別練習傾向（最近6ヶ月）',
    totalPracticeCount: '総練習回数',
    averageDaysPerWeek: '平均日数/週',
    dayOfWeek: '曜日',
    last6Months: '最近6ヶ月',
    
    // Room Management
    room: '部屋',
    createRoom: '部屋を作成',
    joinRoom: '部屋に入室',
    uploadScore: '楽譜をアップロード',
    members: 'メンバー',
    roomName: '部屋名',
    roomDescription: '部屋の説明',
    roomPassword: '合言葉',
    roomId: '部屋ID',
    nickname: 'ニックネーム',
    scoreTitle: '楽譜タイトル',
    composer: '作曲者',
    pageCount: 'ページ数',
    
    // Organization Management
    organizationManagement: '音楽団体管理',
    organizationManagementSubtitle: '練習日程・出欠席・課題を効率的に管理',
    createNewOrganization: '新しい組織を作成',
    joinOrganization: '組織に参加',
    participatingOrganizations: '参加中の組織',
    allOrganizations: '全組織',
    allOrganizationsSubtitle: '参加中の全組織の練習日程・出欠登録・課題を表示',
    open: '開く',
    individualOrganizations: '個別組織',
    noOrganizationsYet: 'まだ組織に参加していません',
    noOrganizationsYetSubtitle: '新しい組織を作成するか、既存の組織に招待を受けてください',
    noDescription: '説明なし',
    createdDate: '作成日',
    unknown: '不明',
    practiceScheduleManagement: '練習日程管理',
    practiceScheduleManagementDesc: '月間カレンダーで練習日を管理し、合奏・パート練・イベントを色分け表示',
    attendanceManagement: '出欠席管理',
    attendanceManagementDesc: '練習日の5日前から当日まで出欠を登録。メンバーも集計結果を確認可能',
    taskManagement: '課題管理',
    taskManagementDesc: 'パートリーダーが練習課題を登録し、メンバーの進捗を把握',
    organizationName: '組織名',
    organizationNamePlaceholder: '例：音楽大学管弦楽部、バンド名など',
    createInSoloMode: 'ソロモードで作成する',
    passwordAutoGenerated: '※ 参加パスワードは自動生成されます。組織作成後に表示されます。',
    soloModeNote: '※ ソロモードでは、パスワードや招待コードは不要です。個人で管理する組織を作成します。',
    description: '説明',
    descriptionPlaceholder: '組織の説明を入力',
    creating: '作成中...',
    createOrganization: '組織を作成',
    searchOrganizationByName: '組織名で検索',
    selectedOrganization: '選択された組織',
    organizationPassword: 'パスワード',
    joining: '参加中...',
    join: '組織に参加',
    organizationCreated: '🎉 組織作成完了！',
    organizationCreatedDesc: '組織「{name}」が正常に作成されました。',
    sharePassword: '💡 このパスワードをメンバーに共有してください。メンバーはこのパスワードを使って組織に参加できます。',
    soloModeCreated: '🎵 ソロモードで作成されました。個人で練習を管理できます。',
    allOrganizationsMenu: '全組織メニュー',
    allOrganizationsCalendar: '全組織の練習日程',
    allOrganizationsCalendarDesc: '参加中の全組織の練習日程をカレンダーで表示',
    practiceSchedule: '練習日程',
    allOrganizationsAttendance: '全組織の出欠登録',
    allOrganizationsAttendanceDesc: '参加中の全組織の出欠登録可能な日程を一覧表示',
    allOrganizationsTasks: '全組織の課題一覧',
    allOrganizationsTasksDesc: '参加中の全組織の課題を一覧表示',
    error: 'エラー',
    pleaseEnterOrganizationName: '組織名を入力してください',
    success: '成功',
    joinedOrganization: '組織に参加しました！',
    pleaseEnterOrganizationAndPassword: '組織とパスワードを入力してください',
    searchResult: '検索結果',
    noOrganizationsFound: '該当する組織が見つかりませんでした',
    multipleOrganizationsFound: '複数の組織が見つかりました',
    organizationJoinPassword: '音楽団体への参加パスワード',
    sharePasswordMessage: 'このパスワードを使って組織に参加してください。',
    
    // Organization Settings & Dashboard
    organizationSettings: '組織設定',
    organizationDashboard: '組織ダッシュボード',
    organization: '組織',
    organizationInfo: '組織情報',
    inviteMember: 'メンバーを招待',
    editOrganization: '組織を編集',
    deleteOrganization: '組織を削除',
    organizationCredentials: '認証情報',
    adminCode: '管理者コード',
    setAdminCode: '管理者コードを設定',
    enterAdminCode: '管理者コードを入力',
    adminCodeMustBe4Digits: '管理者コードは4桁の数字である必要があります',
    adminCodeMismatch: '管理者コードが一致しません',
    pleaseEnterAdminCode: '管理者コードを入力してください',
    organizationIdNotFound: '組織IDが取得できません',
    shareCredentials: '参加情報の共有',
    shareCredentialsTitle: '参加情報の共有',
    copyCredentials: '認証情報をコピー',
    credentialsCopied: '認証情報がクリップボードにコピーされました',
    shareFailed: '共有に失敗しました。もう一度お試しください。',
    copyFailed: 'コピーに失敗しました。もう一度お試しください。',
    previousShareNotCompleted: '前回の共有がまだ完了していません。しばらく待ってから再試行してください。',
    organizationJoinInfo: '音楽団体「{name}」への参加情報',
    organizationJoinInfoMessage: '参加パスワード: {password}\n\nこのパスワードを使って組織に参加してください。',
    deleteOrganizationConfirm: 'この操作は取り消せません。本当に組織を削除しますか？',
    removeMember: 'メンバーを削除',
    removeMemberConfirm: '{name}を組織から削除しますか？',
    memberRemoved: 'メンバーを削除しました',
    memberRemoveFailed: 'メンバーの削除に失敗しました',
    practiceScheduleDesc: '月間カレンダーで練習日を管理',
    organizationSettingsDesc: 'メンバー・権限の管理',
    thisMonthSchedules: '今月の予定',
    moreSchedules: '他{count}件の予定があります',
    scheduleCount: '{count}件の予定',
    ensemble: '合奏',
    partPractice: 'パート練',
    individualPractice: '個人練',
    rehearsal: 'リハーサル',
    lesson: 'レッスン',
    event: 'イベント',
    memberManagement: 'メンバー管理',
    invite: '招待',
    noMembersRegistered: 'メンバーが登録されていません',
    inviteNewMember: '新しいメンバーを招待してください',
    memberName: 'メンバー名',
    emailAddress: 'メールアドレス',
    joinDate: '参加日',
    admin: '管理者',
    leader: 'リーダー',
    member: 'メンバー',
    pleaseEnterEmail: 'メールアドレスを入力してください',
    memberInviteFailed: 'メンバーの招待に失敗しました',
    memberInviteInProgress: 'メンバー招待機能は実装中です',
    info: '情報',
  };

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children?: React.ReactNode }> = ({ children }) => {
  const t = (key: keyof typeof translations): string => {
    return (translations as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ t, language: 'ja', setLanguage: async () => {} }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};