import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { supabase } from '@/lib/supabase';
import { getLanguageSetting } from '@/repositories/userSettingsRepository';

type Language = 'ja' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.ja) => string;
}

const translations = {
  ja: {
    // Navigation
    calendar: 'カレンダー',
    timer: 'タイマー',
    goals: '目標',
    tuner: 'チューナー',
    metronome: 'メトロノーム',
    share: '共有',
    practice: '基礎練',
    practiceMenu: '学習ツール',
    settings: 'その他',
    
    // Common
    save: '保存',
    cancel: 'キャンセル',
    delete: '削除',
    edit: '編集',
    add: '追加',
    close: '閉じる',
    start: 'スタート',
    pause: '一時停止',
    reset: 'リセット',
    search: '検索',
    done: '完了',
    copy: 'コピー',
    copyCompleted: 'コピー完了',
    copiedToClipboard: 'がクリップボードにコピーされました',
    share: '共有',
    
    // Calendar
    practiceCalendar: '練習カレンダー',
    addPracticeRecord: '練習記録を追加',
    practiceTime: '練習時間',
    practiceContent: '練習内容',
    monthlyTotal: '今月の合計練習時間',
    quickRecord: 'クイック記録',
    
    // Timer
    timerMode: 'タイマー',
    stopwatchMode: 'ストップウォッチ',
    customTimeSetting: 'カスタム時間設定',
    quickSetting: 'クイック設定',
    practiceCompleted: '練習完了！',
    recordToCalendar: 'この練習時間をカレンダーに記録しますか？',
    hours: '時間',
    minutes: '分',
    seconds: '秒',
    apply: '適用',
    autoRecord: '次回から自動で記録',
    autoRecordDescription: 'タイマー完了時に自動で練習記録を保存',
    soundOnCompletion: '完了時にサウンド',
    soundOnCompletionDescription: 'タイマー完了時に通知音を再生',
    pleaseSetTimerTime: 'タイマー時間を設定してください',
    settingsCompleted: '設定完了',
    willAutoRecordNextTime: '次回から自動で記録されます',
    timerSetTo: '{time}に設定しました',
    pleaseSetValidTime: '有効な時間を設定してください',
    failedToSavePracticeRecord: '練習記録の保存に失敗しました',
    
    // Goals
    goalSetting: '目標設定',
    personalShort: '個人目標（短期）',
    personalLong: '個人目標（長期）',
    groupGoal: '団体目標',
    addNewGoal: '新しい目標を追加',
    goalTitle: '目標タイトル',
    goalDescription: '詳細説明',
    targetDate: '目標期日',
    progress: '進捗',
    
    // Tuner
    tunerTitle: 'チューナー',
    referenceSound: '基準音再生',
    pitchDetection: '音程検出',
    tuningTips: 'チューニングのコツ',
    cents: 'セント',
    frequency: '周波数',
    featureUnavailable: '機能停止',
    tunerUnavailable: 'チューナー機能は現在利用できません。',
    notSupported: '未対応',
    openStringWebOnly: '開放弦の音はWebでのみ再生できます。',
    failedToPlaySound: '音の再生に失敗しました。',
    
    // Practice
    basicPracticeMenu: 'バイオリンの基礎練メニュー',
    basicPractice: '基礎練',
    beginner: '初級',
    intermediate: '中級',
    advanced: 'マスター',
    basicPracticeMenuFor: '{instrument}の基礎練メニュー',
    
    // Practice Menu
    learningTools: '学習ツール',
    musicDictionary: '音楽用語辞典',
    sightReadingTraining: '譜読みトレーニング',
    
    // Beginner Guide
    faq: 'よくあるQ&A',
    roadmap: '4週間ロードマップ',
    overview: '楽器の基本情報',
    basicPlaying: '基本的な演奏方法',
    fingering: '運指表',
    terminology: '基本楽器用語',
    maintenance: 'メンテナンス',
    tips: '練習のコツ',
    resources: '参考資料',
    basicStructure: '基本構造',
    charm: '魅力',
    history: '歴史・背景',
    features: '特徴',
    famousMusicians: '有名な演奏家',
    howToHold: '楽器の持ち方・構え方',
    howToMakeSound: '基本的な音の出し方',
    fingeringBasics: '基本的な運指表',
    howToUseFingering: '運指表の使い方',
    correctPosture: '正しい姿勢',
    bowHold: '弓の持ち方',
    handPosition: '手の位置',
    leftHand: '左手の使い方',
    embouchure: 'アンブシュア',
    strumming: 'ストラミング（ギター）',
    breathing: '呼吸法（管楽器）',
    fingerUsage: '指の使い方・運指の基礎',
    basicInfo: '基本情報',
    playingMethod: '演奏方法',
    care: 'お手入れ',
    advice: 'アドバイス',
    guide: 'ガイド',
    loading: '読み込み中...',
    maintenanceFrequency: 'メンテナンス頻度の目安',
    practiceTipsAndMindset: '練習のコツ・心構え',
    instrumentGuide: '{instrument}ガイド',
    maintenance: 'お手入れ方法',
    dailyCare: '日常的なお手入れ',
    storageMethod: '保管方法',
    cleaningFrequency: '洗浄頻度の目安',
    precautions: '注意事項',
    requiredSupplies: '必要な用品',
    beginnerAdvice: '初心者向けアドバイス',
    commonMistakes: 'よくある間違いと対策',
    improvementPoints: '上達のためのポイント',
    tutorialVideos: '解説動画',
    
    // Settings
    other: 'その他',
    profile: 'プロフィール設定',
    appearance: '外観設定',
    language: '言語設定',
    notifications: '通知設定',
    statistics: '統計・分析',
    musicLibrary: '楽曲ライブラリ',
    help: 'ヘルプ・サポート',
    feedback: 'フィードバック',
    privacy: 'プライバシー設定',
    terms: '利用規約',
    logout: 'ログアウト',
    createNewAccount: '新規アカウント作成',
    currentlyLoggedIn: 'ログイン中',
    profileSettings: 'プロフィール設定',
    profileSettingsSubtitle: '個人情報・楽器設定',
    myLibrary: 'マイライブラリ',
    myLibrarySubtitle: '楽曲を整理する',
    recordingsLibrary: '録音ライブラリ',
    recordingsLibrarySubtitle: '演奏履歴を時系列で確認',
    mainFeatures: '主要機能',
    mainFeaturesSubtitle: '楽器選択・外観設定',
    tutorial: 'チュートリアル',
    tutorialSubtitle: 'アプリの使い方を学ぶ',
    notificationSettings: '通知設定',
    notificationSettingsSubtitle: '練習リマインダー・通知方法',
    languageSettings: '言語設定',
    languageSettingsSubtitle: '日本語・English',
    privacySettings: 'プライバシー設定',
    privacySettingsSubtitle: '利用規約・プライバシーポリシー',
    feedbackTitle: 'フィードバック',
    feedbackSubtitle: 'アプリをシェア・レビュー・ランキング',
    logoutTitle: 'ログアウト',
    logoutSubtitle: 'アカウントからログアウト',
    logoutConfirm: 'ログアウト確認',
    logoutMessage: 'ログアウトしますか？\n\nログアウト一個上に配置してあるフィードバックにご協力お願いします',
    logoutFailed: 'ログアウトに失敗しました',
    logoutError: 'ログアウト処理中にエラーが発生しました',
    mainFeaturesSettings: '主要機能設定',
    tunerSettings: 'チューナー',
    instrumentSelection: '楽器選択',
    practiceLevel: '演奏レベル',
    appearanceSettings: '外観設定',
    themeLoading: 'テーマの読み込み中...',
    
    // Auth
    login: 'ログイン',
    signup: '新規会員登録',
    email: 'メールアドレス',
    password: 'パスワード',
    confirmPassword: 'パスワード確認',
    loginRequired: 'ログインが必要です',
    
    // Statistics
    statisticsAnalysis: '統計・分析',
    practiceStatsSummary: '練習統計サマリー',
    totalPracticeTime: '総練習時間',
    totalPracticeDays: '総練習日数',
    dailyAverage: '日平均（分）',
    weeklyAverage: '週平均',
    displayPeriod: '表示期間',
    daily: '日毎',
    monthly: '月毎',
    yearly: '年毎',
    averagePracticeTime: '平均練習時間',
    longestPracticeTime: '最長練習時間',
    practiceDays: '練習日数',
    practicedMonths: '練習した月数',
    practicedSections: '練習した区分数',
    weeklyStats: '週別統計',
    monthlyStats: '月別統計',
    yearlyStats: '年別統計',
    detailedAnalysis: '詳細分析',
    basicStats: '基礎統計',
    longestConsecutiveDays: '最長連続練習日',
    practiceIntensityStats: '練習強度別統計',
    shortTime: '短時間（30分未満）',
    mediumTime: '中時間（30-60分）',
    longTime: '長時間（60分以上）',
    times: '回',
    days: '日',
    months: 'ヶ月',
    sections: '区分',
    weekByWeek: '週別',
    monthByMonth: '月別',
    practiceFrequency: '練習頻度',
    weeklyPracticePattern: '週間練習パターン',
    monthlyPracticeTrend: '月別練習傾向（最近6ヶ月）',
    practiceStatsSummary: '練習統計サマリー',
    totalPracticeCount: '総練習回数',
    averageDaysPerWeek: '平均日数/週',
    dayOfWeek: '曜日',
    last6Months: '最近6ヶ月',
    
    // Room Management
    room: '部屋',
    createRoom: '部屋を作成',
    joinRoom: '部屋に入室',
    uploadScore: '楽譜をアップロード',
    members: 'メンバー',
    roomName: '部屋名',
    roomDescription: '部屋の説明',
    roomPassword: '合言葉',
    roomId: '部屋ID',
    nickname: 'ニックネーム',
    scoreTitle: '楽譜タイトル',
    composer: '作曲者',
    pageCount: 'ページ数',
    
    // Organization Management
    organizationManagement: '音楽団体管理',
    organizationManagementSubtitle: '練習日程・出欠席・課題を効率的に管理',
    createNewOrganization: '新しい組織を作成',
    joinOrganization: '組織に参加',
    participatingOrganizations: '参加中の組織',
    allOrganizations: '全組織',
    allOrganizationsSubtitle: '参加中の全組織の練習日程・出欠登録・課題を表示',
    open: '開く',
    individualOrganizations: '個別組織',
    noOrganizationsYet: 'まだ組織に参加していません',
    noOrganizationsYetSubtitle: '新しい組織を作成するか、既存の組織に招待を受けてください',
    loading: '読み込み中...',
    noDescription: '説明なし',
    createdDate: '作成日',
    unknown: '不明',
    mainFeatures: '主な機能',
    practiceScheduleManagement: '練習日程管理',
    practiceScheduleManagementDesc: '月間カレンダーで練習日を管理し、合奏・パート練・イベントを色分け表示',
    attendanceManagement: '出欠席管理',
    attendanceManagementDesc: '練習日の5日前から当日まで出欠を登録。メンバーも集計結果を確認可能',
    taskManagement: '課題管理',
    taskManagementDesc: 'パートリーダーが練習課題を登録し、メンバーの進捗を把握',
    organizationName: '組織名',
    organizationNamePlaceholder: '例：音楽大学管弦楽部、バンド名など',
    createInSoloMode: 'ソロモードで作成する',
    passwordAutoGenerated: '※ 参加パスワードは自動生成されます。組織作成後に表示されます。',
    soloModeNote: '※ ソロモードでは、パスワードや招待コードは不要です。個人で管理する組織を作成します。',
    description: '説明',
    descriptionPlaceholder: '組織の説明を入力',
    creating: '作成中...',
    createOrganization: '組織を作成',
    searchOrganizationByName: '組織名で検索',
    selectedOrganization: '選択された組織',
    organizationPassword: 'パスワード',
    joining: '参加中...',
    join: '組織に参加',
    organizationCreated: '🎉 組織作成完了！',
    organizationCreatedDesc: '組織「{name}」が正常に作成されました。',
    sharePassword: '💡 このパスワードをメンバーに共有してください。メンバーはこのパスワードを使って組織に参加できます。',
    soloModeCreated: '🎵 ソロモードで作成されました。個人で練習を管理できます。',
    allOrganizationsMenu: '全組織メニュー',
    allOrganizationsCalendar: '全組織の練習日程',
    allOrganizationsCalendarDesc: '参加中の全組織の練習日程をカレンダーで表示',
    practiceSchedule: '練習日程',
    allOrganizationsAttendance: '全組織の出欠登録',
    allOrganizationsAttendanceDesc: '参加中の全組織の出欠登録可能な日程を一覧表示',
    allOrganizationsTasks: '全組織の課題一覧',
    allOrganizationsTasksDesc: '参加中の全組織の課題を一覧表示',
    error: 'エラー',
    pleaseEnterOrganizationName: '組織名を入力してください',
    success: '成功',
    joinedOrganization: '組織に参加しました！',
    pleaseEnterOrganizationAndPassword: '組織とパスワードを入力してください',
    searchResult: '検索結果',
    noOrganizationsFound: '該当する組織が見つかりませんでした',
    multipleOrganizationsFound: '複数の組織が見つかりました',
    organizationJoinPassword: '音楽団体への参加パスワード',
    sharePasswordMessage: 'このパスワードを使って組織に参加してください。',
    
    // Organization Settings & Dashboard
    organizationSettings: '組織設定',
    organizationDashboard: '組織ダッシュボード',
    organization: '組織',
    members: 'メンバー',
    organizationInfo: '組織情報',
    inviteMember: 'メンバーを招待',
    editOrganization: '組織を編集',
    deleteOrganization: '組織を削除',
    organizationCredentials: '認証情報',
    adminCode: '管理者コード',
    setAdminCode: '管理者コードを設定',
    enterAdminCode: '管理者コードを入力',
    adminCodeMustBe4Digits: '管理者コードは4桁の数字である必要があります',
    adminCodeMismatch: '管理者コードが一致しません',
    pleaseEnterAdminCode: '管理者コードを入力してください',
    organizationIdNotFound: '組織IDが取得できません',
    shareCredentials: '参加情報の共有',
    shareCredentialsTitle: '参加情報の共有',
    copyCredentials: '認証情報をコピー',
    credentialsCopied: '認証情報がクリップボードにコピーされました',
    shareFailed: '共有に失敗しました。もう一度お試しください。',
    copyFailed: 'コピーに失敗しました。もう一度お試しください。',
    previousShareNotCompleted: '前回の共有がまだ完了していません。しばらく待ってから再試行してください。',
    organizationJoinInfo: '音楽団体「{name}」への参加情報',
    organizationJoinInfoMessage: '参加パスワード: {password}\n\nこのパスワードを使って組織に参加してください。',
    deleteOrganizationConfirm: 'この操作は取り消せません。本当に組織を削除しますか？',
    removeMember: 'メンバーを削除',
    removeMemberConfirm: '{name}を組織から削除しますか？',
    memberRemoved: 'メンバーを削除しました',
    memberRemoveFailed: 'メンバーの削除に失敗しました',
    practiceSchedule: '練習日程',
    practiceScheduleDesc: '月間カレンダーで練習日を管理',
    attendanceManagement: '出欠席管理',
    attendanceManagementDesc: '出席・欠席・遅刻を管理',
    taskManagement: '課題管理',
    taskManagementDesc: '練習課題と進捗を管理',
    organizationSettingsDesc: 'メンバー・権限の管理',
    thisMonthSchedules: '今月の予定',
    moreSchedules: '他{count}件の予定があります',
    scheduleCount: '{count}件の予定',
    ensemble: '合奏',
    partPractice: 'パート練',
    individualPractice: '個人練',
    rehearsal: 'リハーサル',
    lesson: 'レッスン',
    event: 'イベント',
    memberManagement: 'メンバー管理',
    invite: '招待',
    noMembersRegistered: 'メンバーが登録されていません',
    inviteNewMember: '新しいメンバーを招待してください',
    memberName: 'メンバー名',
    emailAddress: 'メールアドレス',
    joinDate: '参加日',
    admin: '管理者',
    leader: 'リーダー',
    member: 'メンバー',
    pleaseEnterEmail: 'メールアドレスを入力してください',
    memberInviteFailed: 'メンバーの招待に失敗しました',
    memberInviteInProgress: 'メンバー招待機能は実装中です',
    info: '情報',
  },
  en: {
    // Navigation
    calendar: 'Calendar',
    timer: 'Timer',
    goals: 'Goals',
    tuner: 'Tuner',
    metronome: 'Metronome',
    share: 'Share',
    practice: 'Practice',
    practiceMenu: 'Learning Tools',
    settings: 'Settings',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    start: 'Start',
    pause: 'Pause',
    reset: 'Reset',
    search: 'Search',
    done: 'Done',
    copy: 'Copy',
    copyCompleted: 'Copy Completed',
    copiedToClipboard: 'has been copied to clipboard',
    share: 'Share',
    
    // Calendar
    practiceCalendar: 'Practice Calendar',
    addPracticeRecord: 'Add Practice Record',
    practiceTime: 'Practice Time',
    practiceContent: 'Practice Content',
    monthlyTotal: 'Monthly Total Practice Time',
    quickRecord: 'Quick Record',
    
    // Timer
    timerMode: 'Timer',
    stopwatchMode: 'Stopwatch',
    customTimeSetting: 'Custom Time Setting',
    quickSetting: 'Quick Setting',
    practiceCompleted: 'Practice Completed!',
    recordToCalendar: 'Would you like to record this practice time to the calendar?',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    apply: 'Apply',
    autoRecord: 'Auto Record Next Time',
    autoRecordDescription: 'Automatically save practice record when timer completes',
    soundOnCompletion: 'Sound on Completion',
    soundOnCompletionDescription: 'Play notification sound when timer completes',
    pleaseSetTimerTime: 'Please set timer time',
    settingsCompleted: 'Settings Completed',
    willAutoRecordNextTime: 'Will auto record from next time',
    timerSetTo: 'Timer set to {time}',
    pleaseSetValidTime: 'Please set a valid time',
    failedToSavePracticeRecord: 'Failed to save practice record',
    
    // Goals
    goalSetting: 'Goal Setting',
    personalShort: 'Personal Goal (Short-term)',
    personalLong: 'Personal Goal (Long-term)',
    groupGoal: 'Group Goal',
    addNewGoal: 'Add New Goal',
    goalTitle: 'Goal Title',
    goalDescription: 'Description',
    targetDate: 'Target Date',
    progress: 'Progress',
    
    // Tuner
    tunerTitle: 'Tuner',
    referenceSound: 'Reference Sound',
    pitchDetection: 'Pitch Detection',
    tuningTips: 'Tuning Tips',
    cents: 'Cents',
    frequency: 'Frequency',
    featureUnavailable: 'Feature Unavailable',
    tunerUnavailable: 'Tuner feature is currently unavailable.',
    notSupported: 'Not Supported',
    openStringWebOnly: 'Open string sounds can only be played on Web.',
    failedToPlaySound: 'Failed to play sound.',
    
    // Practice
    basicPracticeMenu: 'Violin Basic Practice Menu',
    basicPractice: 'Basic Practice',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Master',
    basicPracticeMenuFor: '{instrument} Basic Practice Menu',
    
    // Practice Menu
    learningTools: 'Learning Tools',
    musicDictionary: 'Music Dictionary',
    sightReadingTraining: 'Sight Reading Training',
    
    // Beginner Guide
    faq: 'FAQ',
    roadmap: '4-Week Roadmap',
    overview: 'Basic Instrument Information',
    basicPlaying: 'Basic Playing Method',
    fingering: 'Fingering Chart',
    terminology: 'Basic Instrument Terms',
    maintenance: 'Maintenance',
    tips: 'Practice Tips',
    resources: 'Resources',
    basicStructure: 'Basic Structure',
    charm: 'Charm',
    history: 'History & Background',
    features: 'Features',
    famousMusicians: 'Famous Musicians',
    howToHold: 'How to Hold the Instrument',
    howToMakeSound: 'How to Make Sound',
    fingeringBasics: 'Basic Fingering Chart',
    howToUseFingering: 'How to Use Fingering Chart',
    correctPosture: 'Correct Posture',
    bowHold: 'Bow Hold',
    handPosition: 'Hand Position',
    leftHand: 'Left Hand Usage',
    embouchure: 'Embouchure',
    strumming: 'Strumming (Guitar)',
    breathing: 'Breathing (Wind Instruments)',
    fingerUsage: 'Finger Usage & Fingering Basics',
    basicInfo: 'Basic Info',
    playingMethod: 'Playing Method',
    care: 'Care',
    advice: 'Advice',
    guide: 'Guide',
    loading: 'Loading...',
    maintenanceFrequency: 'Maintenance Frequency Guide',
    practiceTipsAndMindset: 'Practice Tips & Mindset',
    instrumentGuide: '{instrument} Guide',
    maintenance: 'Maintenance',
    dailyCare: 'Daily Care',
    storageMethod: 'Storage Method',
    cleaningFrequency: 'Cleaning Frequency Guide',
    precautions: 'Precautions',
    requiredSupplies: 'Required Supplies',
    beginnerAdvice: 'Beginner Advice',
    commonMistakes: 'Common Mistakes & Solutions',
    improvementPoints: 'Improvement Points',
    tutorialVideos: 'Tutorial Videos',
    
    // Settings
    other: 'Settings',
    profile: 'Profile Settings',
    appearance: 'Appearance Settings',
    language: 'Language Settings',
    notifications: 'Notification Settings',
    statistics: 'Statistics & Analysis',
    musicLibrary: 'Music Library',
    help: 'Help & Support',
    feedback: 'Feedback',
    privacy: 'Privacy Settings',
    terms: 'Terms of Service',
    logout: 'Logout',
    createNewAccount: 'Create New Account',
    currentlyLoggedIn: 'Currently Logged In',
    profileSettings: 'Profile Settings',
    profileSettingsSubtitle: 'Personal information & instrument settings',
    myLibrary: 'My Library',
    myLibrarySubtitle: 'Organize your music',
    recordingsLibrary: 'Recordings Library',
    recordingsLibrarySubtitle: 'View performance history chronologically',
    mainFeatures: 'Main Features',
    mainFeaturesSubtitle: 'Instrument selection, appearance settings',
    tutorial: 'Tutorial',
    tutorialSubtitle: 'Learn how to use the app',
    notificationSettings: 'Notification Settings',
    notificationSettingsSubtitle: 'Practice reminders & notification methods',
    languageSettings: 'Language Settings',
    languageSettingsSubtitle: 'Japanese & English',
    privacySettings: 'Privacy Settings',
    privacySettingsSubtitle: 'Terms of service, privacy policy',
    feedbackTitle: 'Feedback',
    feedbackSubtitle: 'Share app, review, ranking',
    logoutTitle: 'Logout',
    logoutSubtitle: 'Log out from account',
    logoutConfirm: 'Logout Confirmation',
    logoutMessage: 'Do you want to logout?\n\nPlease help us by providing feedback above the logout button',
    logoutFailed: 'Logout failed',
    logoutError: 'An error occurred during logout',
    mainFeaturesSettings: 'Main Features Settings',
    tunerSettings: 'Tuner',
    instrumentSelection: 'Instrument Selection',
    practiceLevel: 'Practice Level',
    appearanceSettings: 'Appearance Settings',
    themeLoading: 'Loading theme...',
    
    // Auth
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginRequired: 'Login required',
    
    // Statistics
    statisticsAnalysis: 'Statistics & Analysis',
    practiceStatsSummary: 'Practice Statistics Summary',
    totalPracticeTime: 'Total Practice Time',
    totalPracticeDays: 'Total Practice Days',
    dailyAverage: 'Daily Average (min)',
    weeklyAverage: 'Weekly Average',
    displayPeriod: 'Display Period',
    daily: 'Daily',
    monthly: 'Monthly',
    yearly: 'Yearly',
    averagePracticeTime: 'Average Practice Time',
    longestPracticeTime: 'Longest Practice Time',
    practiceDays: 'Practice Days',
    practicedMonths: 'Practiced Months',
    practicedSections: 'Practiced Sections',
    weeklyStats: 'Weekly Statistics',
    monthlyStats: 'Monthly Statistics',
    yearlyStats: 'Yearly Statistics',
    detailedAnalysis: 'Detailed Analysis',
    basicStats: 'Basic Statistics',
    longestConsecutiveDays: 'Longest Consecutive Practice Days',
    practiceIntensityStats: 'Practice Intensity Statistics',
    shortTime: 'Short Time (under 30 min)',
    mediumTime: 'Medium Time (30-60 min)',
    longTime: 'Long Time (60+ min)',
    times: 'times',
    days: 'days',
    months: 'months',
    sections: 'sections',
    weekByWeek: 'Week by Week',
    monthByMonth: 'Month by Month',
    practiceFrequency: 'Practice Frequency',
    weeklyPracticePattern: 'Weekly Practice Pattern',
    monthlyPracticeTrend: 'Monthly Practice Trend (Last 6 Months)',
    practiceStatsSummary: 'Practice Statistics Summary',
    totalPracticeCount: 'Total Practice Count',
    averageDaysPerWeek: 'Average Days/Week',
    dayOfWeek: 'Day of Week',
    last6Months: 'Last 6 Months',
    
    // Room Management
    room: 'Room',
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    uploadScore: 'Upload Score',
    members: 'Members',
    roomName: 'Room Name',
    roomDescription: 'Room Description',
    roomPassword: 'Password',
    roomId: 'Room ID',
    nickname: 'Nickname',
    scoreTitle: 'Score Title',
    composer: 'Composer',
    pageCount: 'Page Count',
    
    // Organization Management
    organizationManagement: 'Organization Management',
    organizationManagementSubtitle: 'Efficiently manage practice schedules, attendance, and tasks',
    createNewOrganization: 'Create New Organization',
    joinOrganization: 'Join Organization',
    participatingOrganizations: 'Participating Organizations',
    allOrganizations: 'All Organizations',
    allOrganizationsSubtitle: 'View practice schedules, attendance, and tasks for all participating organizations',
    open: 'Open',
    individualOrganizations: 'Individual Organizations',
    noOrganizationsYet: 'Not participating in any organizations yet',
    noOrganizationsYetSubtitle: 'Create a new organization or accept an invitation to an existing one',
    loading: 'Loading...',
    noDescription: 'No description',
    createdDate: 'Created Date',
    unknown: 'Unknown',
    mainFeatures: 'Main Features',
    practiceScheduleManagement: 'Practice Schedule Management',
    practiceScheduleManagementDesc: 'Manage practice days with monthly calendar, color-coded for ensemble, section practice, and events',
    attendanceManagement: 'Attendance Management',
    attendanceManagementDesc: 'Register attendance from 5 days before to the practice day. Members can also view aggregated results',
    taskManagement: 'Task Management',
    taskManagementDesc: 'Section leaders register practice tasks and track member progress',
    organizationName: 'Organization Name',
    organizationNamePlaceholder: 'e.g., Music University Orchestra, Band Name, etc.',
    createInSoloMode: 'Create in Solo Mode',
    passwordAutoGenerated: '※ Participation password will be auto-generated and displayed after organization creation.',
    soloModeNote: '※ In Solo Mode, passwords and invitation codes are not required. Create an organization for personal management.',
    description: 'Description',
    descriptionPlaceholder: 'Enter organization description',
    creating: 'Creating...',
    createOrganization: 'Create Organization',
    searchOrganizationByName: 'Search by Organization Name',
    selectedOrganization: 'Selected Organization',
    organizationPassword: 'Password',
    joining: 'Joining...',
    join: 'Join Organization',
    organizationCreated: '🎉 Organization Created!',
    organizationCreatedDesc: 'Organization "{name}" has been successfully created.',
    sharePassword: '💡 Share this password with members. Members can use this password to join the organization.',
    soloModeCreated: '🎵 Created in Solo Mode. You can manage your practice personally.',
    allOrganizationsMenu: 'All Organizations Menu',
    allOrganizationsCalendar: 'All Organizations Calendar',
    allOrganizationsCalendarDesc: 'View practice schedules for all participating organizations in calendar',
    practiceSchedule: 'Practice Schedule',
    allOrganizationsAttendance: 'All Organizations Attendance',
    allOrganizationsAttendanceDesc: 'List all attendance-registerable dates for all participating organizations',
    allOrganizationsTasks: 'All Organizations Tasks',
    allOrganizationsTasksDesc: 'List all tasks for all participating organizations',
    error: 'Error',
    pleaseEnterOrganizationName: 'Please enter organization name',
    success: 'Success',
    joinedOrganization: 'Successfully joined the organization!',
    pleaseEnterOrganizationAndPassword: 'Please enter organization and password',
    searchResult: 'Search Result',
    noOrganizationsFound: 'No matching organizations found',
    multipleOrganizationsFound: 'Multiple organizations found',
    organizationJoinPassword: 'Organization Join Password',
    sharePasswordMessage: 'Use this password to join the organization.',
    
    // Organization Settings & Dashboard
    organizationSettings: 'Organization Settings',
    organizationDashboard: 'Organization Dashboard',
    organization: 'Organization',
    members: 'Members',
    organizationInfo: 'Organization Info',
    inviteMember: 'Invite Member',
    editOrganization: 'Edit Organization',
    deleteOrganization: 'Delete Organization',
    organizationCredentials: 'Credentials',
    adminCode: 'Admin Code',
    setAdminCode: 'Set Admin Code',
    enterAdminCode: 'Enter Admin Code',
    adminCodeMustBe4Digits: 'Admin code must be 4 digits',
    adminCodeMismatch: 'Admin codes do not match',
    pleaseEnterAdminCode: 'Please enter admin code',
    organizationIdNotFound: 'Organization ID not found',
    shareCredentials: 'Share Credentials',
    shareCredentialsTitle: 'Share Join Information',
    copyCredentials: 'Copy Credentials',
    credentialsCopied: 'Credentials have been copied to clipboard',
    shareFailed: 'Share failed. Please try again.',
    copyFailed: 'Copy failed. Please try again.',
    previousShareNotCompleted: 'Previous share is not completed yet. Please wait a moment and try again.',
    organizationJoinInfo: 'Join Information for "{name}"',
    organizationJoinInfoMessage: 'Join Password: {password}\n\nUse this password to join the organization.',
    deleteOrganizationConfirm: 'This action cannot be undone. Are you sure you want to delete this organization?',
    removeMember: 'Remove Member',
    removeMemberConfirm: 'Remove {name} from the organization?',
    memberRemoved: 'Member removed successfully',
    memberRemoveFailed: 'Failed to remove member',
    practiceSchedule: 'Practice Schedule',
    practiceScheduleDesc: 'Manage practice days with monthly calendar',
    attendanceManagement: 'Attendance Management',
    attendanceManagementDesc: 'Manage attendance, absence, and tardiness',
    taskManagement: 'Task Management',
    taskManagementDesc: 'Manage practice tasks and progress',
    organizationSettingsDesc: 'Manage members and permissions',
    thisMonthSchedules: 'This Month\'s Schedules',
    moreSchedules: '{count} more schedules',
    scheduleCount: '{count} schedules',
    ensemble: 'Ensemble',
    partPractice: 'Part Practice',
    individualPractice: 'Individual Practice',
    rehearsal: 'Rehearsal',
    lesson: 'Lesson',
    event: 'Event',
    memberManagement: 'Member Management',
    invite: 'Invite',
    noMembersRegistered: 'No members registered',
    inviteNewMember: 'Please invite a new member',
    memberName: 'Member Name',
    emailAddress: 'Email Address',
    joinDate: 'Join Date',
    admin: 'Admin',
    leader: 'Leader',
    member: 'Member',
    pleaseEnterEmail: 'Please enter email address',
    memberInviteFailed: 'Failed to invite member',
    memberInviteInProgress: 'Member invitation feature is under development',
    info: 'Info',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children?: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('ja');

  useEffect(() => {
    loadLanguage();
  }, []);

  const loadLanguage = async () => {
    try {
      // まずAsyncStorageから読み込む（高速）
      const savedLanguage = await AsyncStorage.getItem('app_language');
      if (savedLanguage && (savedLanguage === 'ja' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }

      // データベースから言語設定を読み込む（認証済みユーザーの場合）
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (user) {
          const result = await getLanguageSetting(user.id);
          if (result.data && (result.data === 'ja' || result.data === 'en')) {
            // データベースの設定を優先
            setLanguageState(result.data);
            // AsyncStorageも更新
            await AsyncStorage.setItem('app_language', result.data);
          }
        }
      } catch (dbError) {
        // データベース読み込みエラーは無視（AsyncStorageの値を使用）
        console.warn('データベースから言語設定を読み込めませんでした:', dbError);
      }
    } catch (error) {
      // デフォルト言語を使用
      console.warn('言語設定の読み込みエラー:', error);
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      await AsyncStorage.setItem('app_language', lang);
      setLanguageState(lang);
    } catch (error) {
      // 言語保存エラー
    }
  };

  const t = (key: keyof typeof translations.ja): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};