import { StyleSheet } from 'react-native';
import { createShadowStyle } from '@/lib/shadowStyles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  content: {
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom: 80,
  },
  modeToggle: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 0,
    marginTop: 20,
    marginBottom: 12,
    elevation: 4,
    overflow: 'hidden',
  },
  modeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    minHeight: 44,
    borderRadius: 12,
    gap: 6,
  },
  modeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 0,
  },
  timerContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 4,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 8,
    elevation: 0,
    position: 'relative',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    ...createShadowStyle({
      shadowColor: 'transparent',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    }),
  },
  circularProgressContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    marginVertical: 0,
  },
  timerCenterContent: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  timerTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
    color: '#FFFFFF',
  },
  timerDisplay: {
    fontSize: 48,
    fontWeight: '700',
    fontFamily: 'monospace',
    color: '#00D4FF',
    marginBottom: 8,
  },
  alarmTimeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  alarmIcon: {
    fontSize: 16,
    marginRight: 4,
  },
  alarmTime: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FF6B35',
  },
  controlButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    marginTop: 20,
  },
  controlButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 0,
  },
  completedIndicator: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: '#4CAF50',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  completedText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
  },
  timerSettings: {
    marginBottom: 4,
  },
  customTimeContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 12,
    marginBottom: 6,
    elevation: 4,
    overflow: 'hidden',
    width: '100%',
  },
  wheelsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
  },
  wheelBlock: {
    alignItems: 'center',
  },
  wheelLabel: {
    fontSize: 12,
    marginBottom: 4,
  },
  wheelColon: {
    fontSize: 18,
    fontWeight: '700',
    marginHorizontal: 4,
  },
  applyButton: {
    backgroundColor: '#8B4513',
    borderRadius: 12,
    paddingVertical: 3,
    alignItems: 'center',
  },
  applyButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  settingsContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    elevation: 4,
  },
  settingsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333333',
    marginBottom: 16,
    textAlign: 'center',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  settingLeft: {
    flex: 1,
    marginRight: 16,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  settingDescription: {
    fontSize: 12,
    lineHeight: 16,
  },
  testSoundButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    marginRight: 8,
  },
  testSoundButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  smallChoiceButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    marginLeft: 4,
  },
  stopwatchContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    width: '100%',
  },
  stopwatchTimeContainer: {
    width: '100%',
    paddingVertical: 40,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    ...createShadowStyle({
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
    }),
    marginBottom: 20,
  },
  stopwatchTime: {
    fontSize: 56,
    fontWeight: '700',
    fontFamily: 'monospace',
    letterSpacing: 1,
    textAlign: 'center',
  },
  stopwatchControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    width: '100%',
    paddingHorizontal: 20,
  },
  stopwatchButton: {
    minWidth: 100,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
    elevation: 2,
    ...createShadowStyle({
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    }),
  },
  stopwatchMainButton: {
    minWidth: 120,
    height: 64,
    borderRadius: 32,
  },
  stopwatchButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  lapTimesContainer: {
    width: '100%',
    maxWidth: 400,
    marginTop: 20,
    padding: 16,
    borderRadius: 16,
    maxHeight: 300,
    elevation: 2,
    ...createShadowStyle({
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
    }),
  },
  lapTimesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  lapTimesTitle: {
    fontSize: 14,
    fontWeight: '600',
  },
  clearLapsButton: {
    fontSize: 12,
    fontWeight: '600',
  },
  lapTimesList: {
    maxHeight: 240,
  },
  lapTimeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
  },
  lapNumber: {
    fontSize: 13,
    fontWeight: '600',
    minWidth: 50,
    color: '#666',
  },
  lapTimeText: {
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'monospace',
    flex: 1,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  lapTotalTime: {
    fontSize: 13,
    fontWeight: '500',
    fontFamily: 'monospace',
    minWidth: 90,
    textAlign: 'right',
    color: '#999',
  },
  largeControlButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
  },
});
