import { StyleSheet, Platform } from 'react-native';
import { createShadowStyle } from '@/lib/shadowStyles';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  content: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 4,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#333333',
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#007AFF',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  addGoalForm: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    elevation: 4,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333333',
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 16,
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
  },
  textArea: {
    height: 80,
    textAlignVertical: 'top',
  },
  buttonRow: {
    flexDirection: 'row',
    marginBottom: 16,
    gap: 8,
  },
  typeButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    alignItems: 'center',
  },
  typeButtonActive: {
    backgroundColor: '#8B4513',
    borderColor: '#8B4513',
  },
  typeButtonText: {
    fontSize: 12,
    color: '#666666',
  },
  typeButtonTextActive: {
    color: '#FFFFFF',
  },
  saveButton: {
    backgroundColor: '#8B4513',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  goalsList: {
    gap: 8,
  },
  goalCard: {
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    marginBottom: 8,
    marginHorizontal: 0,
    ...createShadowStyle({
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    }),
    elevation: 3,
  },
  goalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
    position: 'relative',
    zIndex: 1,
  },
  goalHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  goalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  goalTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
    lineHeight: 22,
    letterSpacing: -0.3,
  },
  goalDescription: {
    fontSize: 13,
    marginBottom: 4,
    lineHeight: 18,
  },
  progressText: {
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
  },

  deleteButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FF4444',
    zIndex: 10,
    ...createShadowStyle({
      shadowColor: '#FF4444',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    }),
    elevation: 2,
  },
  deleteButtonText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    lineHeight: 20,
  },
  achievementIcon: {
    marginLeft: 4,
  },
  // 新しいセクション用のスタイル
  section: {
    marginBottom: 16,
    padding: 16,
    borderRadius: 12,
    elevation: 3,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  goalTypes: {
    gap: 12,
    marginBottom: 16,
  },
  goalTypeCard: {
    padding: 16,
    borderWidth: 2,
    borderRadius: 12,
    backgroundColor: '#F8F9FA',
    flex: 1,
  },
  goalTypeTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  goalTypeDescription: {
    fontSize: 14,
    lineHeight: 20,
    flexWrap: 'wrap',
  },
  addGoalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 24,
    gap: 8,
  },

  targetSongCard: {
    paddingVertical: 8, // 12から8に短縮
    paddingHorizontal: 16,
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  targetSongTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    lineHeight: 22,
    flexWrap: 'wrap',
  },
  targetSongComposer: {
    fontSize: 14,
    marginBottom: 0,
  },
  targetSongNotes: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    gap: 6,
    alignSelf: 'flex-start',
    backgroundColor: '#E8E8E8',
  },
  editButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  addTargetSongButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 20,
    gap: 6,
  },
  addTargetSongText: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  performanceSlots: {
    gap: 16,
  },
  performanceSlot: {
    gap: 8,
  },
  slotLabel: {
    fontSize: 14,
    fontWeight: '600',
  },
  performanceCard: {
    paddingVertical: 8, // 12から8に短縮
    paddingHorizontal: 16,
    marginBottom: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  performanceTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
    lineHeight: 20,
    flexWrap: 'wrap',
  },
  performanceDescription: {
    fontSize: 14,
    color: '#666',
    marginBottom: 12,
    lineHeight: 18,
  },
  performanceUrlRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginBottom: 8,
  },
  performanceUrl: {
    fontSize: 14,
    flex: 1,
    marginRight: 10,
  },
  performanceButtons: {
    flexDirection: 'row',
    gap: 8,
  },
  playButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    gap: 6,
  },
  playButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  performanceActions: {
    flexDirection: 'row',
    gap: 8,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    paddingHorizontal: 0,
    borderRadius: 6,
    gap: 2,
    ...createShadowStyle({
      shadowColor: '#4CAF50',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    }),
    elevation: 3,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  actionButtonOld: {
    padding: 8,
    borderRadius: 0,
    minWidth: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addPerformanceButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderStyle: 'solid',
    borderRadius: 16,
    gap: 4,
  },
  addPerformanceText: {
    fontSize: 16,
    fontWeight: '600',
  },
  completedSection: {
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  completedSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  completedSectionTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  completedGoalCard: {
    opacity: 0.85,
    borderWidth: 1,
    borderColor: '#E8F5E9',
  },
  completedGoalBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 0,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  completedGoalBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  completedGoalTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    lineHeight: 22,
    flexWrap: 'wrap',
  },
  completedGoalDescription: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  completedGoalDate: {
    fontSize: 12,
    fontStyle: 'italic',
  },
  emptyText: {
    fontSize: 16,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  // イベント用のスタイル
  addEventButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 0,
    gap: 8,
    marginBottom: 16,
  },
  addEventButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  eventCard: {
    padding: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 0,
    marginBottom: 12,
  },
  eventHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    marginRight: 16,
  },
  eventActions: {
    flexDirection: 'row',
    gap: 8,
  },
  eventActionButton: {
    padding: 8,
    borderRadius: 0,
    minWidth: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventDate: {
    fontSize: 14,
    marginBottom: 8,
  },
  eventDescription: {
    fontSize: 14,
    lineHeight: 20,
  },
  // 達成済みイベント用のスタイル
  completedEventCard: {
    padding: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 0,
    marginBottom: 12,
  },
  completedEventTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  completedEventDate: {
    fontSize: 14,
    marginBottom: 8,
  },
  completedEventDescription: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  completedEventCompletionDate: {
    fontSize: 12,
    fontStyle: 'italic',
  },
  // モーダル用のスタイル
  modalContainer: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  modalCloseButton: {
    padding: 8,
  },
  modalCloseText: {
    fontSize: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  modalSaveButton: {
    padding: 8,
  },
  modalSaveText: {
    fontSize: 16,
    fontWeight: '600',
  },
  modalContent: {
    flex: 1,
    padding: 20,
  },
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
  },
  formInput: {
    borderWidth: 1,
    borderRadius: 0,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
  },
  formTextArea: {
    borderWidth: 1,
    borderRadius: 0,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 100,
  },
  // 日付入力用のスタイル
  dateInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  calendarButton: {
    padding: 12,
    borderRadius: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // カレンダー用のスタイル
  calendarOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarModal: {
    width: 320,
    borderRadius: 16,
    padding: 20,
    elevation: 10,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  calendarNavButton: {
    padding: 8,
    borderRadius: 8,
  },
  calendarTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  weekdayHeader: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  weekdayText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
  },
  calendarDay: {
    width: '14.28%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    margin: 1,
  },
  calendarDayOtherMonth: {
    opacity: 0.3,
  },
  calendarDaySelected: {
    backgroundColor: '#8B4513',
  },
  calendarDayText: {
    fontSize: 14,
    fontWeight: '500',
  },
  calendarDayTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  calendarCloseButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  calendarCloseButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  // 横分割セクション用のスタイル
  splitSectionContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  splitSection: {
    flex: 1,
    padding: 16,
    borderRadius: 0,
  },
  splitSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  composerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  videoPlayerContainer: {
    flex: 1,
  },
  videoPlayerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
  },
  videoPlayerCloseButton: {
    padding: 8,
  },
  videoPlayerCloseText: {
    fontSize: 16,
  },
  videoPlayerTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
  videoPlayerHeaderSpacer: {
    width: 40, // ボタン間のスペースを調整
  },
  videoWebView: {
    flex: 1,
  },
  // 空状態表示用のスタイル
  emptyState: {
    alignItems: 'center',
    paddingVertical: 20,
    marginBottom: 16,
  },
  emptyStateText: {
    fontSize: 16,
    marginBottom: 10,
  },
  goalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  goalDeadline: {
    fontSize: 14,
  },
  goalActions: {
    flexDirection: 'row',
    gap: 8,
    alignSelf: 'flex-end',
    marginTop: 8,
  },
  addButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  progressBar: {
    flex: 1,
    height: 5,
    borderRadius: 5,
    overflow: 'hidden',
    marginBottom: 4,
  },
  progressFill: {
    height: '100%',
    borderRadius: 6,
  },
  progressButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 2,
  },
  calendarToggleRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    gap: 0,
    marginTop: 8,
    marginHorizontal: 0,
    paddingHorizontal: 0,
  },
  calendarToggleButtons: {
    flexDirection: 'row',
    gap: 0,
    flexWrap: 'nowrap',
    flex: 1,
    marginRight: 0,
  },
  calendarToggleBtn: {
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderRadius: 0,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 28,
    flex: 1,
    marginHorizontal: 0,
  },
  calendarToggleText: {
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  progressButton: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 8,
    minWidth: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressButtonMinus: {
    backgroundColor: '#F5F5F5',
    borderWidth: 1.5,
    borderColor: '#E0E0E0',
  },
  progressButtonPlus: {
    borderWidth: 0,
  },
  progressButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#333333',
  },
  shortGoalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 6,
  },
  achievementBadgeInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginLeft: 'auto',
  },
  achievementBadgeInlineFull: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
    justifyContent: 'center',
  },
  achievementText: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  progressButtonsWithBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  progressBarCompact: {
    flex: 1,
    height: 6,
    borderRadius: 6,
    overflow: 'hidden',
    backgroundColor: '#E5E5E5',
  },
  progressPercentageCompact: {
    fontSize: 12,
    fontWeight: '700',
    minWidth: 40,
    textAlign: 'right',
  },
  progressSliderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    marginTop: 4,
  },
  progressSliderTrack: {
    flex: 1,
    height: 12,
    borderRadius: 8,
    backgroundColor: '#E5E5E5',
    overflow: 'hidden',
    ...createShadowStyle({
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 1,
    }),
  },
  progressSliderFill: {
    height: '100%',
    borderRadius: 8,
    ...createShadowStyle({
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    }),
  },
  progressPercentageLabel: {
    fontSize: 16,
    fontWeight: '700',
    minWidth: 50,
    textAlign: 'right',
    letterSpacing: 0.5,
  },
  completeButtonContainer: {
    marginTop: 4,
    alignItems: 'center',
  },
  completeAndHideRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  completeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 0,
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
    gap: 6,
    marginLeft: 0,
    ...createShadowStyle({
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 2,
    }),
  },
  completeButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  achievementBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 16,
    gap: 8,
    ...createShadowStyle({
      shadowColor: '#4CAF50',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 3,
    })
  },
  achievementBadgeSuccess: {
    backgroundColor: '#4CAF50',
  },
  bigAchievementBadge: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 20,
    transform: [{ scale: 1.02 }],
  },
  achievementBadgeText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  bigAchievementText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  justCompletedOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 16,
  },
  justCompletedText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 1,
  },
  goalDate: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 2,
  },
  goalDateText: {
    fontSize: 11,
    marginLeft: 6,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  progressSection: {
    marginTop: 2,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  progressLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#666666',
    letterSpacing: 0.2,
  },
  progressPercentage: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  goalTypeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 4,
  },
  goalTypeBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  dateInput: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 48,
  },
  dateInputText: {
    fontSize: 16,
    flex: 1,
  },
  simpleGoalForm: {
    marginTop: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 8,
  },
  characterCount: {
    fontSize: 12,
    textAlign: 'right',
    marginTop: 4,
  },
  dateSelectorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  yearMonthSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  monthSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectorButton: {
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minWidth: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectorButtonText: {
    fontSize: 12,
    fontWeight: '600',
  },
  yearMonthText: {
    fontSize: 16,
    fontWeight: '600',
    minWidth: 80,
    textAlign: 'center',
  },
  calendarToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    gap: 8,
  },
  calendarToggleButtons: {
    flexDirection: 'row',
    gap: 8,
    flex: 1,
  },
  calendarToggleBtn: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarToggleText: {
    fontSize: 13,
    fontWeight: '600',
  },
  calendarToggleActions: {
    flexDirection: 'row',
    gap: 4,
    marginTop: 4,
  },
  calendarToggleButton: {
    flex: 1,
    paddingVertical: 4,
    paddingHorizontal: 0,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 0,
    minWidth: 0,
  },
  calendarToggleButtonText: {
    fontSize: 12,
    fontWeight: '600',
    marginHorizontal: 0,
    paddingHorizontal: 0,
  },
});