import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  content: {
    flex: 1,
    paddingHorizontal: 1,
  },
  modeToggleContainer: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    borderRadius: 12,
    padding: 0,
    marginTop: 12,
    marginBottom: 2,
    marginHorizontal: 16,
    elevation: 4,
    overflow: 'hidden',
  },
  modeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    minHeight: 44,
    borderRadius: 12,
    gap: 6,
  },
  modeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 0,
  },
  mainDisplay: {
    width: '100%',
    borderRadius: 20,
    padding: 16,
    marginBottom: 4,
    alignItems: 'center',
    elevation: 8,
  },
  startButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginBottom: 8,
    elevation: 4,
  },
  startButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  tunerCard: {
    width: '100%',
    maxWidth: 480,
    height: 320,
    borderRadius: 16,
    borderWidth: 2,
    paddingVertical: 24,
    paddingHorizontal: 24,
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  noteDisplayContainer: {
    position: 'relative',
    width: 120,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  notePlaceholder: {
    position: 'absolute',
    fontSize: 72,
    fontWeight: '700',
  },
  noteName: {
    fontSize: 72,
    fontWeight: 'bold',
    position: 'absolute',
    color: '#2C3E50',
    textAlign: 'center',
    width: 120,
    height: 100,
    lineHeight: 100,
    ...(Platform.OS === 'web' ? {
      textShadow: '1px 1px 2px rgba(0, 0, 0, 0.1)',
    } : {
      textShadowColor: 'rgba(0, 0, 0, 0.1)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    }),
  },
  frequencyValue: {
    fontSize: 18,
    marginBottom: 20,
    fontFamily: 'monospace',
    color: '#34495E',
    fontWeight: '600',
    backgroundColor: '#F8F9FA',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E9ECEF',
  },
  // 新しいチューニングバースタイル
  tuningBarContainer: {
    width: '100%',
    height: 60, // 固定高さを設定
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 16,
    justifyContent: 'center',
  },
  tuningBarTrack: {
    width: '95%',
    height: 20,
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    position: 'relative',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    overflow: 'hidden',
  },
  centerLine: {
    position: 'absolute',
    left: '50%',
    top: 0,
    width: 3,
    height: 20,
    backgroundColor: '#2C2C2C',
    marginLeft: -1.5,
    borderRadius: 1.5,
  },
  referenceLine: {
    position: 'absolute',
    top: 0,
    width: 2,
    height: 20,
    backgroundColor: '#666666',
    marginLeft: -1,
  },
  minorLine: {
    position: 'absolute',
    top: 5,
    width: 1,
    height: 10,
    backgroundColor: '#999999',
    marginLeft: -0.5,
  },
  tuningIndicator: {
    position: 'absolute',
    top: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    marginLeft: -4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    transform: [{ translateX: -4 }],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  tuningBarBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
  },
  centsLabels: {
    position: 'absolute',
    top: 25,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  centsDisplay: {
    fontSize: 16,
    color: '#333333',
    fontFamily: 'monospace',
    textAlign: 'center',
    fontWeight: '600',
    marginTop: 8,
  },
  // プロ仕様の品質表示スタイル
  qualityIndicator: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#F8F9FA',
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: '#E9ECEF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  qualityText: {
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  // 設定パネル
  settingsPanel: {
    marginTop: 16,
    padding: 12,
    borderRadius: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    marginHorizontal: 0,
  },
  settingsTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 16,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  settingRow: {
    marginBottom: 12,
  },
  currentInstrumentDisplay: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginTop: 6,
    alignItems: 'center',
  },
  currentInstrumentText: {
    fontSize: 16,
    fontWeight: '600',
  },
  displayModeSelector: {
    flexDirection: 'row',
    marginTop: 8,
  },
  displayModeButton: {
    flex: 1,
    paddingVertical: 10,
    marginHorizontal: 2,
    borderRadius: 8,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  displayModeButtonText: {
    fontSize: 14,
    fontWeight: '500',
  },
  frequencyAdjuster: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  frequencyButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  frequencyButtonText: {
    fontSize: 18,
    fontWeight: '600',
  },
  directionDisplay: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
    color: '#444444',
  },
  // メトロノーム用スタイル
  timeSignatureContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  timeSignatureLabel: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 8,
  },
  timeSignatureDisplay: {
    fontSize: 48,
    fontWeight: '700',
  },
  bpmContainer: {
    alignItems: 'center',
    marginBottom: 30,
  },
  bpmLabel: {
    fontSize: 16,
    fontWeight: '500',
    marginBottom: 8,
  },
  bpmValue: {
    fontSize: 72,
    fontWeight: '700',
    fontFamily: 'monospace',
  },
  beatIndicators: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  beatIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginHorizontal: 8,
  },
  settingsContainer: {
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    elevation: 4,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: '500',
  },
  bpmAdjustContainer: {
    marginBottom: 20,
  },
  bpmAdjustControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  bpmAdjustButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    elevation: 2,
  },
  bpmAdjustButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  bpmDisplay: {
    fontSize: 24,
    fontWeight: '700',
    fontFamily: 'monospace',
    marginHorizontal: 20,
  },
  timeSignatureSettingContainer: {
    marginBottom: 20,
  },
  timeSignatureSettingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
  },
  timeSignatureSettingButton: {
    width: 60,
    height: 60,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 3,
  },
  timeSignatureSettingButtonText: {
    fontSize: 16,
    fontWeight: '700',
  },
  metronomeSoundSettingContainer: {
    marginBottom: 20,
  },
  metronomeSoundSettingGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginTop: 8,
  },
  metronomeSoundSettingButton: {
    minWidth: 80,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  metronomeSoundSettingButtonText: {
    fontSize: 14,
    fontWeight: '600',
  },
  metronomeStartButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 24,
    elevation: 4,
    marginTop: 20,
  },
  metronomeStartButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 8,
  },
  // カスタムカラーチューナーのスタイル
  customTunerContainer: {
    borderRadius: 16,
    overflow: 'hidden',
    marginTop: 2,
    backgroundColor: '#F5F5F5', // ライトグレー色
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  customDisplayArea: {
    backgroundColor: '#FFFFFF', // 白色
    padding: 12,
    alignItems: 'center',
  },
  customNoteDisplay: {
    alignItems: 'center',
    marginBottom: 12,
  },
  customNoteName: {
    fontSize: 72,
    fontWeight: '700',
    marginBottom: 4,
  },
  customFrequency: {
    fontSize: 24,
    fontWeight: '600',
  },
  customArcMeter: {
    width: 220,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  customArcBackground: {
    width: 220,
    height: 120,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  customArcMark: {
    position: 'absolute',
    width: 2,
    borderRadius: 1,
  },
  customCentLabel: {
    position: 'absolute',
  },
  customCentLabelText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#2F2F2F',
  },
  customZeroMark: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#2F2F2F',
  },
  customZeroMarkText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#2F2F2F',
  },
  customTargetPointer: {
    position: 'absolute',
  },
  customTriangleLeft: {
    width: 0,
    height: 0,
    borderLeftWidth: 8,
    borderRightWidth: 0,
    borderBottomWidth: 6,
    borderLeftColor: '#2F2F2F',
    borderRightColor: 'transparent',
    borderBottomColor: 'transparent',
  },
  customTriangleRight: {
    width: 0,
    height: 0,
    borderLeftWidth: 0,
    borderRightWidth: 8,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: '#2F2F2F',
    borderBottomColor: 'transparent',
  },
  customNeedle: {
    position: 'absolute',
    width: 2,
    height: 50,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  customNeedleLine: {
    width: 2,
    height: 50,
    borderRadius: 1,
  },
  customControlPanel: {
    backgroundColor: '#F5F5F5', // ライトグレー色
    padding: 20,
    alignItems: 'center',
  },
  customStatusIndicators: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  customFlatSymbol: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
    marginRight: 20,
  },
  customSharpSymbol: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
    marginLeft: 20,
  },
  customLedContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  customLed: {
    width: 16,
    height: 16,
    borderRadius: 8,
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  // 楽器別説明のスタイル
  instrumentInfo: {
    marginTop: 16,
    padding: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.05)',
    borderRadius: 10,
  },
  instrumentInfoTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  instrumentInfoText: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  tuningNotes: {
    marginTop: 8,
  },
  tuningNotesTitle: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
  },
  tuningNote: {
    fontSize: 13,
    marginBottom: 4,
    paddingLeft: 8,
  },
  // 音名表示モードセクションのスタイル（統合版）
  noteDisplayModeSection: {
    width: '100%',
    marginTop: 16,
    padding: 20,
    borderRadius: 16,
    marginHorizontal: 0,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  noteDisplayModeHeader: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  noteDisplayModeTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  noteDisplayModeButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  noteDisplayModeButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 2,
  },
  noteDisplayModeButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  // 開放弦コンテンツのスタイル
  openStringContent: {
    marginTop: 0,
  },
  openStringTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
  },
  openStringDescription: {
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
  },
  openStringButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 0,
  },
  openStringButton: {
    width: '48%',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    minHeight: 80,
  },
  openStringButtonText: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 2,
    textAlign: 'center',
  },
  openStringFrequency: {
    fontSize: 14,
    fontWeight: '500',
    opacity: 0.8,
    textAlign: 'center',
  },
  openStringLabel: {
    fontSize: 12,
    fontWeight: '400',
    opacity: 0.7,
    marginTop: 2,
    textAlign: 'center',
  },
  stopButton: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    elevation: 2,
  },
  stopButtonText: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  playingIndicator: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
    textAlign: 'center',
    opacity: 0.9,
  },
  // シンプルなチューナーのスタイル
  simpleTunerContainer: {
    width: '100%',
    padding: 24,
    borderRadius: 16,
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    overflow: 'hidden', // 枠内の要素がはみ出さないように
  },
  simpleNoteContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    minHeight: 110, // 固定高さを設定してレイアウトシフトを防ぐ（小さく調整）
    height: 110, // 固定高さ（小さく調整）
  },
  simpleNoteWrapper: {
    flexDirection: 'row',
    alignItems: 'center', // baselineからcenterに変更して中央揃えを確実にする
    justifyContent: 'center',
    alignSelf: 'center', // 中央揃えを確実にする
    marginLeft: 24, // もっと右にシフト
  },
  simpleNoteName: {
    fontSize: 72, // 96から72に縮小
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 1.5, // 2から1.5に縮小
    includeFontPadding: false, // フォントパディングを無効化してレイアウトシフトを防ぐ
  },
  simpleOctave: {
    fontSize: 36, // 48から36に縮小
    fontWeight: '600',
    marginLeft: 6, // 8から6に縮小
    textAlign: 'center', // leftからcenterに変更
    includeFontPadding: false, // フォントパディングを無効化
  },
  simpleFrequency: {
    fontSize: 20,
    fontWeight: '500',
    marginBottom: 32,
    fontFamily: 'monospace',
  },
  simpleTuningBarContainer: {
    width: '100%',
    marginBottom: 32,
    alignItems: 'center',
  },
  simpleTuningBarTrack: {
    width: '100%',
    height: 8,
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    position: 'relative',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#BDBDBD',
  },
  simpleCenterLine: {
    position: 'absolute',
    left: '50%',
    top: 0,
    width: 2,
    height: 8,
    marginLeft: -1,
    borderRadius: 1,
  },
  simpleMark: {
    position: 'absolute',
    width: 1,
    top: 0,
    marginLeft: -0.5,
    borderRadius: 0.5,
  },
  simpleIndicator: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    top: -2,
    marginLeft: -6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  simpleCentsContainer: {
    height: 28, // セント表示の固定高さを確保
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 8,
  },
  simpleCents: {
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'monospace',
    textAlign: 'center',
  },
  simpleStartButton: {
    paddingVertical: 16,
    paddingHorizontal: 48,
    borderRadius: 24,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  simpleStartButtonText: {
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1,
  },
});